name: Otaku Codes
description: Life of an Otaku, coding its way, to become No. 1
meta_description: "Life of an Otaku, coding its way, to become No. 1"

favicon: '/assets/images/otaku.png'

markdown: kramdown
permalink: /:categories/:title.html
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://otaku.codes'
google_analytics: 'UA-97043938-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://otaku.codes'
author:         'Viraj "Inf3cti0n95" Trivedi'
authordesc: A Creative FrontEnd Developer, A BackEnd Developer with OCD for performance, An Artist, An Otaku.
